# The goal is to let this action deploy both actions for Github and libs for npm
# from https://github.com/e-square-io/nx-github-actions/blob/main/.github/workflows/main.yml
# follow up of work for github action ncc build within nx setup
# see https://github.com/nrwl/nx/issues/5005
# About th authentication through a Github App
# see https://dev.to/dtinth/authenticating-as-a-github-app-in-a-github-actions-workflow-27co
name: CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'chore(release)') }}
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{ steps.affected.outputs.hasChanges }}
      matrix: ${{ steps.affected.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      # - name: Cache npm
      #   uses: actions/cache@v2
      #   with:
      #     path: .npm
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm-
      #       ${{ runner.os }}-
      
      - name: Install Dependencies
        run: npm ci --cache .npm
      
      - name: Calculate affected
        uses: e-square-io/nx-affected-matrix@v2
        id: affected
        with:
          # targets: 'test,build'
          targets: 'build'
          maxDistribution: '10'

  execute:
    name: ${{ matrix.target }} (${{ matrix.distribution }})
    if: ${{ needs.setup.outputs.hasChanges }}
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --cache .npm

      - name: Run semantic-release locally
        id: release
        if: ${{ matrix.target == 'build' }}
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["main"]'
          node-module: true
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package.json version
        if: ${{ matrix.target == 'build' && steps.release.outputs.released }}
        run: |
          for path in ./packages/*; do
            if [[ -f "$path/package.json" ]]; then
              (cd $path && npm version --no-git-tag-version ${{ steps.release.outputs.version }})
            fi
          done

      - name: Execute target
        uses: e-square-io/nx-distributed-task@v2
        id: run
        with:
          nxCloud: true
          target: ${{ matrix.target }}
          projects: ${{ matrix.projects }}

  # coverage:
  #   name: Publish coverage
  #   runs-on: ubuntu-latest
  #   needs: [setup, execute]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Download artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: test

  #     - uses: codecov/codecov-action@v1
  #       with:
  #         directory: ./coverage/packages/*

  release:
    name: Release version
    if: ${{ needs.setup.outputs.hasChanges }}
    runs-on: ubuntu-latest
    needs: [setup, execute]
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Run semantic-release
        id: release
        uses: ridedott/release-me-action@master
        with:
          release-branches: '["main"]'
          node-module: true
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Update git tags
      #   if: ${{ steps.release.outputs.released }}
      #   run: |
      #     git config --global hub.protocol https
      #     git config user.name knitkode
      #     git config user.email knitkode@gmail.com
      #     git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/knitkode/kjam.git"
      #     git remote set-url --push origin "https://x-access-token:$GITHUB_TOKEN@github.com/knitkode/kjam.git"
      #     git tag -fa v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
      #     git tag -fa v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
      #     git push -f --tags
      #   env:
      #     GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}

  publish:
    name: Publish
    if: ${{ needs.release.outputs.released }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ['cli', 'core', 'next', 'next-ui', 'action-next']
    needs: [setup, execute, release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Publish action kjam-${{ matrix.package }}
        if: ${{ contains(needs.setup.outputs.matrix, matrix.package) && startsWith(matrix.package, 'action-') }}
        uses: symplify/monorepo-split-github-action@2.0
        env:
          GITHUB_TOKEN: 'x-access-token:${{ steps.githubAppAuth.outputs.token }}'
        with:
          tag: v${{ needs.release.outputs.version }}
          package-directory: './dist/packages/${{ matrix.package }}'
          split-repository-organization: knitkode
          split-repository-name: 'kjam-${{ matrix.package }}'
          user-name: knitkode
          user-email: knitkode@gmail.com

      - name: Update action major and patch version tags
        if: ${{ contains(needs.setup.outputs.matrix, matrix.package) && startsWith(matrix.package, 'action-') }}
        env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
        run: |
          git config --global hub.protocol https
          git config user.name knitkode
          git config user.email knitkode@gmail.com
          git remote rm origin
          git remote add origin "https://x-access-token:$GITHUB_TOKEN@github.com/knitkode/kjam-${{ matrix.package }}.git"
          git fetch -f
          git fetch --tags -f
          git config main.remote origin
          git config main.merge refs/heads/main
          git reset --hard origin/main
          git tag -fa v${{ needs.release.outputs.major }} -m "Release v${{ needs.release.outputs.major }}"
          git tag -fa v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }} -m "Release v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}"
          git push origin -f refs/tags/v${{ needs.release.outputs.major }}
          git push origin -f refs/tags/v${{ needs.release.outputs.major }}.${{ needs.release.outputs.minor }}

      - name: Publish lib @kjam/${{ matrix.package }}
        if: ${{ contains(needs.setup.outputs.matrix, matrix.package) && !startsWith(matrix.package, 'action-') }}
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/packages/${{ matrix.package }}/package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}